force-app/main/default/objects/AsyncJob__c/AsyncJob__c.object-meta.xml
<CustomObject>
    <label>Async Job</label>
    <nameField>
        <displayFormat>AsyncJob-{000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AsyncJobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AsyncJob__c/fields/ExecutionCount__c.field-meta.xml
<CustomField>
    <fullName>ExecutionCount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Represents the number of executions done by specific AsyncJob</description>
    <label>Execution Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AsyncJob__c/fields/IsRecursive__c.field-meta.xml
<CustomField>
    <fullName>IsRecursive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If true runs until the AsyncJobResult returns as Completed</description>
    <label>Is Recursive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AsyncJob__c/fields/JobName__c.field-meta.xml
<CustomField>
    <fullName>JobName__c</fullName>
    <description>The name of the job by which the apex class maps</description>
    <label>Job Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AsyncJob__c/fields/LastExecutionStatus__c.field-meta.xml
<CustomField>
    <fullName>LastExecutionStatus__c</fullName>
    <description>Represents the last execution statu</description>
    <label>Last Execution Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AsyncJob__c/fields/LastExecutionTime__c.field-meta.xml
<CustomField>
    <fullName>LastExecutionTime__c</fullName>
    <description>Represents the last execution time, no matter the status of execution</description>
    <label>Last Execution Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/AsyncJob__c/fields/MaxExecutionCount__c.field-meta.xml
<CustomField>
    <fullName>MaxExecutionCount__c</fullName>
    <defaultValue>5</defaultValue>
    <description>Represents the maximum number of executions allowed, unless it is a recursive AsyncJob</description>
    <label>Max Execution Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AsyncJob__c/fields/Params__c.field-meta.xml
<CustomField>
    <fullName>Params__c</fullName>
    <inlineHelpText>The params that should be initialized in AsyncJob during execution</inlineHelpText>
    <label>Params</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/AsyncJob__c/fields/ResultLog__c.field-meta.xml
<CustomField>
    <fullName>ResultLog__c</fullName>
    <description>Result log for each execution based on the AsyncJobResult</description>
    <label>Result Log</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/AsyncJob__c/fields/RetryInterval__c.field-meta.xml
<CustomField>
    <fullName>RetryInterval__c</fullName>
    <defaultValue>15</defaultValue>
    <description>Represents the delay between the next execution if needed</description>
    <label>Retry Interval</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AsyncJob__c/fields/ScheduleTime__c.field-meta.xml
<CustomField>
    <fullName>ScheduleTime__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <description>The time when the AsyncJob should be executed</description>
    <label>Schedule Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/AsyncJob__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Queued</fullName>
                <default>true</default>
                <label>Queued</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AsyncJobExecutor.cls
public without sharing class AsyncJobExecutor {
    private static final String LOG_SEPARATOR = '\n\n';

    private static AsyncJobService asyncJobService = new AsyncJobService();

    private AsyncJob__c asyncJob;

    private Datetime startTime;
    private Datetime endTime;

    private Long cpuTimeStart;
    private Long cpuTimeEnd;

    public AsyncJobExecutor(AsyncJob__c asyncJob) {
        this.asyncJob = asyncJob;
    }

    public static void executeNow(Id asyncJobId) {
        AsyncJob__c asyncJob = [
            SELECT Id, Status__c, JobName__c, ExecutionCount__c, MaxExecutionCount__c, IsRecursive__c, RetryInterval__c, ScheduleTime__c, ResultLog__c, LastExecutionTime__c, LastExecutionStatus__c, Params__c, CreatedById, CreatedDate
            FROM AsyncJob__c
            WHERE Id = :asyncJobId
        ];

        new AsyncJobExecutor(asyncJob).execute();
    }

    public void execute() {
        AsyncJobResult result;

        this.makeQueued();
        this.addExecutionCount();

        this.startTime = Datetime.now();
        this.cpuTimeStart = Limits.getCpuTime();

        try {
            ASyncJobHandler handler = asyncJobService.toAsyncJobHandler(this.asyncJob);
            result = handler.execute();
        } catch (Exception e) {
            result = AsyncJobResult.toFailedResult(e.getMessage());
        } finally {
            this.endTime = Datetime.now();
            this.cpuTimeEnd = Limits.getCpuTime();
        }
        this.processResult(result);
    }

    private void processResult(AsyncJobResult result) {
        switch on result.status {
            when COMPLETED {
                this.processCompletedResult();
            }
            when SUCCESS {
                this.processSuccessResult();
            }
            when RETRY_LATER {
                this.processRetryLaterResult();
            }
            when FAILED {
                this.processFailedResult();
            }
            when FATAL_ERROR {
                this.closeFailedAsyncJob();
            }
        }

        this.setLastExecutionTime();
        this.setLastExecutionStatus(result.status);
        this.addResultLog(result);

        this.updateAsyncJob();
    }

    private void processCompletedResult() {
        this.closeSucceededAsyncJob();
    }

    private void processSuccessResult() {
        if (this.isRecursive()) {
            this.rescheduleAsyncJob();
        } else {
            this.processCompletedResult();
        }
    }

    private void processRetryLaterResult() {
        if (this.areExecutionLimitsReached()) {
            this.closeFailedAsyncJob();
        } else {
            this.rescheduleAsyncJob();
        }
    }

    private void processFailedResult() {
        if (this.isRecursive()) {
            this.rescheduleAsyncJob();
        } else {
            this.closeFailedAsyncJob();
        }
    }

    private Boolean areExecutionLimitsReached() {
        return this.asyncJob.ExecutionCount__c >= this.asyncJob.MaxExecutionCount__c;
    }

    private Boolean isRecursive() {
        return this.asyncJob.IsRecursive__c;
    }

    private void closeSucceededAsyncJob() {
        this.asyncJob.Status__c = AsyncJobConstants.STATUS.COMPLETED;
    }

    private void closeFailedAsyncJob() {
        this.asyncJob.Status__c = AsyncJobConstants.STATUS.FAILED;
    }

    private void addExecutionCount() {
        this.asyncJob.ExecutionCount__c = (this.asyncJob.ExecutionCount__c ?? 0) + 1;
    }

    private void setLastExecutionTime() {
        this.asyncJob.LastExecutionTime__c = this.endTime;
    }

    private void setLastExecutionStatus(AsyncJobResult.AsyncJobStatus status) {
        this.asyncJob.LastExecutionStatus__c = status.name();
    }

    private void rescheduleAsyncJob() {
        this.asyncJob.ScheduleTime__c = this.asyncJob.ScheduleTime__c.addMinutes((Integer) this.asyncJob.RetryInterval__c);
    }

    private void addResultLog(AsyncJobResult result) {
        List<String> logLines = new List<String>{
            'Execution Time: ' + Datetime.now().format('yyyy-MM-dd HH:mm:ss.S \'GMT\'', 'GMT'),
            'Execution Longevity: ' + (this.endTime.getTime() - this.startTime.getTime()) + ' ms',
            'CPU Time: ' + (this.cpuTimeEnd - this.cpuTimeStart) + ' of ' + Limits.getCpuTime() + ' ms',
            'Status: ' + String.valueOf(result.status),
            'Message: ' + String.valueOf(result.message)
        };

        String resultLog = String.isNotBlank(this.asyncJob.ResultLog__c) ? this.asyncJob.ResultLog__c + LOG_SEPARATOR + String.join(logLines, '\n') : String.join(logLines, '\n');

        this.asyncJob.ResultLog__c = resultLog.right(4000);
    }

    private void makeQueued() {
        this.asyncJob.Status__c = AsyncJobConstants.STATUS.QUEUED;
    }

    private void updateAsyncJob() {
        update this.asyncJob;
    }
}