force-app/main/default/objects/AsyncJob__c/AsyncJob__c.object-meta.xml
<CustomObject>
    <label>Async Job</label>
    <nameField>
        <displayFormat>AsyncJob-{000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AsyncJobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AsyncJob__c/fields/ExecutionCount__c.field-meta.xml
<CustomField>
    <fullName>ExecutionCount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Represents the number of executions done by specific AsyncJob</description>
    <label>Execution Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AsyncJob__c/fields/JobName__c.field-meta.xml
<CustomField>
    <fullName>JobName__c</fullName>
    <description>The name of the job by which the apex class maps</description>
    <label>Job Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AsyncJob__c/fields/LastExecutionStatus__c.field-meta.xml
<CustomField>
    <fullName>LastExecutionStatus__c</fullName>
    <description>Represents the last execution statu</description>
    <label>Last Execution Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AsyncJob__c/fields/LastExecutionTime__c.field-meta.xml
<CustomField>
    <fullName>LastExecutionTime__c</fullName>
    <description>Represents the last execution time, no matter the status of execution</description>
    <label>Last Execution Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/AsyncJob__c/fields/ResultLog__c.field-meta.xml
<CustomField>
    <fullName>ResultLog__c</fullName>
    <description>Result log for each execution based on the AsyncJobResult</description>
    <label>Result Log</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/AsyncJob__c/fields/ScheduleTime__c.field-meta.xml
<CustomField>
    <fullName>ScheduleTime__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <description>The time when the AsyncJob should be executed</description>
    <label>Schedule Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/AsyncJob__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Queued</fullName>
                <default>true</default>
                <label>Queued</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AsyncJobTestUtils.cls
@IsTest
public without sharing class AsyncJobTestUtils {

    public static void executeAsync(String jobName) {
        AsyncJob__c job = findFirstQueuedJobByActionName(jobName);

        if (job == null) {
            throw new AsyncJobException('No queued job found for action name: ' + jobName);
        }

        AsyncJobInvokable.executeAsync(job.Id);
    }

    public static AsyncJob__c findFirstQueuedJobByActionName(String jobName) {
        List<AsyncJob__c> jobs = findJobsByActionName(jobName);

        for (AsyncJob__c job : jobs) {
            if (job.Status__c == AsyncJobConstants.STATUS.QUEUED) {
                return job;
            }
        }

        return null;
    }

    public static AsyncJob__c findFirstJobByActionName(String jobName) {
        List<AsyncJob__c> jobs = findJobsByActionName(jobName);

        return jobs.isEmpty() ? null : jobs[0];
    }

    public static Boolean hasQueuedJobsByActionName(String jobName) {
        return findFirstQueuedJobByActionName(jobName) != null;
    }

    public static List<AsyncJob__c> findQueuedJobsByActionName(String jobName) {
        List<AsyncJob__c> jobs = findJobsByActionName(jobName);

        for (AsyncJob__c job : jobs) {
            if (job.Status__c == AsyncJobConstants.STATUS.QUEUED) {
                jobs.add(job);
            }
        }

        return jobs;
    }

    public static List<AsyncJob__c> findJobsByActionName(String jobName) {
        return [
            SELECT Id, JobName__c, Status__c, LastExecutionStatus__c, ScheduleTime__c, LastExecutionTime__c, ExecutionCount__c, ResultLog__c
            FROM AsyncJob__c
            WHERE JobName__c = :jobName
        ];
    }

}