force-app/main/default/objects/AsyncJob__c/AsyncJob__c.object-meta.xml
<CustomObject>
    <label>Async Job</label>
    <nameField>
        <displayFormat>AsyncJob-{000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AsyncJobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AsyncJob__c/fields/IsRecursive__c.field-meta.xml
<CustomField>
    <fullName>IsRecursive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If true runs until the AsyncJobResult returns as Completed</description>
    <label>Is Recursive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AsyncJob__c/fields/JobName__c.field-meta.xml
<CustomField>
    <fullName>JobName__c</fullName>
    <description>The name of the job by which the apex class maps</description>
    <label>Job Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AsyncJob__c/fields/MaxExecutionCount__c.field-meta.xml
<CustomField>
    <fullName>MaxExecutionCount__c</fullName>
    <defaultValue>5</defaultValue>
    <description>Represents the maximum number of executions allowed, unless it is a recursive AsyncJob</description>
    <label>Max Execution Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AsyncJob__c/fields/Params__c.field-meta.xml
<CustomField>
    <fullName>Params__c</fullName>
    <inlineHelpText>The params that should be initialized in AsyncJob during execution</inlineHelpText>
    <label>Params</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/AsyncJob__c/fields/ParentJobId__c.field-meta.xml
<CustomField>
    <fullName>ParentJobId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>If the AsyncJob was created in context of another AsyncJob the field is populated</description>
    <label>Parent Job Id</label>
    <referenceTo>AsyncJob__c</referenceTo>
    <relationshipName>AsyncJobs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AsyncJob__c/fields/RetryInterval__c.field-meta.xml
<CustomField>
    <fullName>RetryInterval__c</fullName>
    <defaultValue>15</defaultValue>
    <description>Represents the delay between the next execution if needed</description>
    <label>Retry Interval</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AsyncJob__c/fields/ScheduleTime__c.field-meta.xml
<CustomField>
    <fullName>ScheduleTime__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <description>The time when the AsyncJob should be executed</description>
    <label>Schedule Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/AsyncJob__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Queued</fullName>
                <default>true</default>
                <label>Queued</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AsyncJobBuilder.cls
public virtual class AsyncJobBuilder {

    private AsyncJob__c asyncJob;

    public AsyncJobBuilder(String jobName) {
        this.asyncJob = new AsyncJob__c(
            JobName__c = jobName
        );
    }

    public AsyncJobBuilder setParentJobId(Id parentJobId) {
        return this.setValue(AsyncJob__c.ParentJobId__c, parentJobId);
    }

    public AsyncJobBuilder setScheduleTime(Datetime scheduleTime) {
        return this.setValue(AsyncJob__c.ScheduleTime__c, scheduleTime);
    }

    public AsyncJobBuilder setRetryInterval(Integer retryIntervalInMinutes) {
        return this.setValue(AsyncJob__c.RetryInterval__c, retryIntervalInMinutes);
    }

    public AsyncJobBuilder setMaxExecutionCount(Integer maxExecutionCount) {
        return this.setValue(AsyncJob__c.MaxExecutionCount__c, maxExecutionCount);
    }

    public AsyncJobBuilder makeRecursive() {
        return this.setValue(AsyncJob__c.IsRecursive__c, true);
    }

    public AsyncJobBuilder setParams(Map<String, Object> params) {
        return this.setParams(JSON.serialize(params));
    }

    public AsyncJobBuilder setParams(String params) {
        return this.setValue(AsyncJob__c.Params__c, params);
    }

    public AsyncJob__c build() {
        if (this.asyncJob.ParentJobId__c == null) {
            this.setParentJobId(AsyncJobHandler.jobId);
        }

        if (this.asyncJob.ScheduleTime__c == null) {
            this.setScheduleTime(Datetime.now());
            //execute immediately
            this.setValue(AsyncJob__c.Status__c, AsyncJobConstants.STATUS.IN_PROGRESS);
        }

        return this.asyncJob;
    }

    private AsyncJobBuilder setValue(SObjectField field, Object value) {
        this.asyncJob.put(field, value);
        return this;
    }

}