force-app/main/default/objects/AsyncJob__c/AsyncJob__c.object-meta.xml
<CustomObject>
    <label>Async Job</label>
    <nameField>
        <displayFormat>AsyncJob-{000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AsyncJobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AsyncJob__c/fields/AreExecutionLimitsReached__c.field-meta.xml
<CustomField>
    <fullName>AreExecutionLimitsReached__c</fullName>
    <description>Indicates if the ASyncJob can be executed again</description>
    <formula>IF( IsRecursive__c, false,  ExecutionCount__c &gt;=  MaxExecutionCount__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Are Execution Limits Reached</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AsyncJob__c/fields/ScheduleTime__c.field-meta.xml
<CustomField>
    <fullName>ScheduleTime__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <description>The time when the AsyncJob should be executed</description>
    <label>Schedule Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/AsyncJob__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Queued</fullName>
                <default>true</default>
                <label>Queued</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AsyncJobBatch.cls
public without sharing class AsyncJobBatch implements Database.Batchable<SObject> {
    
    public static final String BATCH_JOB_NAME = 'AsyncJobBatch';

    private static final Integer BATCH_SIZE = 50;

    private AsyncJobBatch() {
    }

    public static Id startJob() {
        if (AsyncJobService.isBatchJobActive()) {
            throw new AsyncJobException('Batch job is already running');
        }

        Id jobId = Database.executeBatch(new AsyncJobBatch(), BATCH_SIZE);

        AsyncJobService.setBatchJobId(jobId);

        return jobId;
    }

    public static void abortJob() {
        AsyncJobService.setBatchJobId(null);
    }

    public Database.QueryLocator start(Database.BatchableContext context) {
        AsyncJobService.setBatchJobId(context.getJobId());

        return Database.getQueryLocator([
            SELECT Id
            FROM AsyncJob__c
            WHERE Status__c = :AsyncJobConstants.STATUS.QUEUED
            AND ScheduleTime__c <= :Datetime.now()
            AND AreExecutionLimitsReached__c = FALSE
        ]);
    }

    public void execute(Database.BatchableContext context, List<AsyncJob__c> jobs) {
        List<AsyncJob__c> jobsToExecute = new List<AsyncJob__c>();

        for (AsyncJob__c job : jobs) {
            jobsToExecute.add(new AsyncJob__c(
                Id = job.Id,
                Status__c = AsyncJobConstants.STATUS.IN_PROGRESS
            ));
        }

        update jobsToExecute;
    }

    public void finish(Database.BatchableContext context) {
        String jobName = Test.isRunningTest() ? BATCH_JOB_NAME + '-' + context.getJobId() : BATCH_JOB_NAME;
        AsyncJobService.setBatchJobId(System.scheduleBatch(new AsyncJobBatch(), jobName, 1, BATCH_SIZE));
    }
}