force-app/main/default/objects/AsyncJob__c/AsyncJob__c.object-meta.xml
<CustomObject>
    <label>Async Job</label>
    <nameField>
        <displayFormat>AsyncJob-{000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AsyncJobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AsyncJob__c/fields/ExecutionCount__c.field-meta.xml
<CustomField>
    <fullName>ExecutionCount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Represents the number of executions done by specific AsyncJob</description>
    <label>Execution Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AsyncJob__c/fields/IsRecursive__c.field-meta.xml
<CustomField>
    <fullName>IsRecursive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If true runs until the AsyncJobResult returns as Completed</description>
    <label>Is Recursive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AsyncJob__c/fields/JobName__c.field-meta.xml
<CustomField>
    <fullName>JobName__c</fullName>
    <description>The name of the job by which the apex class maps</description>
    <label>Job Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AsyncJob__c/fields/LastExecutionStatus__c.field-meta.xml
<CustomField>
    <fullName>LastExecutionStatus__c</fullName>
    <description>Represents the last execution statu</description>
    <label>Last Execution Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AsyncJob__c/fields/LastExecutionTime__c.field-meta.xml
<CustomField>
    <fullName>LastExecutionTime__c</fullName>
    <description>Represents the last execution time, no matter the status of execution</description>
    <label>Last Execution Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/AsyncJob__c/fields/MaxExecutionCount__c.field-meta.xml
<CustomField>
    <fullName>MaxExecutionCount__c</fullName>
    <defaultValue>5</defaultValue>
    <description>Represents the maximum number of executions allowed, unless it is a recursive AsyncJob</description>
    <label>Max Execution Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AsyncJob__c/fields/Params__c.field-meta.xml
<CustomField>
    <fullName>Params__c</fullName>
    <inlineHelpText>The params that should be initialized in AsyncJob during execution</inlineHelpText>
    <label>Params</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/AsyncJob__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Queued</fullName>
                <default>true</default>
                <label>Queued</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AsyncJobAction__mdt/AsyncJobAction__mdt.object-meta.xml
<CustomObject>
    <description>Represents the mapping between the JobName and AsyncJobHandler ApexClass</description>
    <label>Async Job Action</label>
    <pluralLabel>Async Job Actions</pluralLabel>
</CustomObject>

force-app/main/default/objects/AsyncJobAction__mdt/fields/AsyncJobHandler__c.field-meta.xml
<CustomField>
    <fullName>AsyncJobHandler__c</fullName>
    <description>Represents the AsyncJobHandler class that the Job Name is mapped to</description>
    <label>Async Job Handler</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AsyncJobAction__mdt/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>The configuration will take place only if active</description>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AsyncJobAction__mdt/fields/JobName__c.field-meta.xml
<CustomField>
    <fullName>JobName__c</fullName>
    <description>The Async Job Name to map by</description>
    <label>Job Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AsyncJobService.cls
public without sharing class AsyncJobService {

    @TestVisible
    private static String CACHE_PARTITION_NAME = 'local.AsyncJobBatchId';
    private static String CACHE_KEY_ACTIVE_JOB_BATCH_ID = 'activeJobBatchId';

    public static final List<String> ACTIVE_JOB_STATUSES = new List<String>{
        AsyncJobConstants.STATUS.QUEUED,
        AsyncJobConstants.STATUS.IN_PROGRESS
    };

    @TestVisible
    private static Map<String, String> mockAsyncJobHandlerByJobName;


    //ToDO add logic to work with cache on ASyncJobBatchId
    public static Boolean isBatchJobActive() {
        try {
            Cache.OrgPartition cachePart = Cache.Org.getPartition(CACHE_PARTITION_NAME);
            return (Id) cachePart.get(CACHE_KEY_ACTIVE_JOB_BATCH_ID) != null;
        } catch (Exception ex) {
            return false;
        }
    }

    //ToDO add logic to work with cache on ASyncJobBatchId
    public static void setBatchJobId(String batchJobId) {
        try {
            Cache.OrgPartition cachePart = Cache.Org.getPartition(CACHE_PARTITION_NAME);
            cachePart.put(CACHE_KEY_ACTIVE_JOB_BATCH_ID, batchJobId);
        } catch (Exception ex) {
        }
    }

    @Future
    public static void restartExecutionProcessAsync(Set<Id> jobIds) {
        updateStatus(jobIds, AsyncJobConstants.STATUS.HOLD);
        updateStatus(jobIds, AsyncJobConstants.STATUS.IN_PROGRESS);
    }

    public AsyncJobHandler toAsyncJobHandler(AsyncJob__c job) {
        String asyncJobHanderClass = getAsyncJobHandlerClass(job.JobName__c);

        if (asyncJobHanderClass == null) {
            throw new AsyncJobException('Active Async job handler class not found for job: ' + job.JobName__c);
        }

        Type handlerType = Type.forName(asyncJobHanderClass);

        if (handlerType == null) {
            throw new AsyncJobException('Async Job handler class "' + asyncJobHanderClass + '" not exist for job: ' + job.JobName__c);
        }

        AsyncJobHandler.jobId = job.Id;
        AsyncJobHandler.createdById = job.CreatedById;

        AsyncJobHandler handler = (AsyncJobHandler) handlerType.newInstance();

        handler.apexClassName = asyncJobHanderClass;
        handler.isRecursive = job.IsRecursive__c;
        handler.createdDate = job.CreatedDate;
        handler.lastExecutionTime = job.LastExecutionTime__c;
        handler.lastExecutionStatus = job.LastExecutionStatus__c;
        handler.executionCount = (Integer) job.ExecutionCount__c;
        handler.maxExecutionCount = (Integer) job.MaxExecutionCount__c;

        handler.setParams(job.Params__c);

        return handler;
    }

    private static void updateStatus(Set<Id> jobIds, String status) {
        List<AsyncJob__c> asyncJobs = new List<AsyncJob__c>();

        for (Id jobId : jobIds) {
            asyncJobs.add(new AsyncJob__c(
                Id = jobId,
                Status__c = status
            ));
        }

        Database.update(asyncJobs, false);
    }

    private String getAsyncJobHandlerClass(String jobName) {
        if (String.isBlank(jobName)) {
            return null;
        }

        if (mockAsyncJobHandlerByJobName != null) {
            return mockAsyncJobHandlerByJobName.get(jobName);
        }

        List<AsyncJobAction__mdt> jobActions = [SELECT Id, AsyncJobHandler__c FROM AsyncJobAction__mdt WHERE JobName__c = :jobName and IsActive__c = TRUE LIMIT 1];

        return jobActions.isEmpty() ? null : jobActions[0].AsyncJobHandler__c;
    }
}